manifests_dir: benchmark/data/manifests
ru_manifest_name: tonebooksplus_validation_ru_100.json
en_manifest_name: librispeech_asr_en_100.json
recreate_manifests: false

ru:
  hf_dataset: Vikhrmodels/ToneBooksPlus
  split: validation
  count: 100
  id_field: id

en:
  hf_dataset: openslr/librispeech_asr
  split: validation.clean
  count: 100
  id_field: id
